# 1)
# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For
# every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user
# guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and
# “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses
# the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random

random_4_numbers = []
attempt = 0

while len(random_4_numbers) < 4:
    x = random.randrange(0, 9)
    random_4_numbers.append(x)
    random_4_numbers = list(set(random_4_numbers))

print('The secrete number is :', random_4_numbers)
print()

finish = False

while not finish:
    attempt += 1
    cows = 0
    bulls = 0
    user_guess = input("Welcome to the Cows and Bulls Game! \nEnter a number: ")
    user_guess_list = [int(user_guess[i]) for i in range(len(user_guess))]

    for i in range(4):
        for j in range(4):
            if user_guess_list[i] == random_4_numbers[j]:
                bulls += 1

    for i in range(4):
        if user_guess_list[i] == random_4_numbers[i]:
            cows += 1
    print("cows: ", cows)
    print("bulls: ", bulls)
    if cows == 4:
        print(f'you have won the game, with {attempt} attempts')
        finish = True
